import React from 'react'
import { Link } from 'react-router-dom'

const Hedar = () => {
  return (
    <div>
      <Link to={'/'}>Intro</Link>........
      <Link to={'/Hobbie'}>Hobbie</Link>......
    <Link to="/contact">Contact</Link> ......
      <Link to={'/about'}>about</Link>......
      <Link to={'/Education'}>Education</Link>.....
      <Link to={'/Exprince'}>Exprince</Link>.....
      <Link to={'/Gole'}>Gole</Link>.....
      <Link to={'/'}>Hedar</Link>.....
      <Link to={'/Project'}>Project</Link>.....
      <Link to={'/skill'}>skill</Link>
     

    </div>
  )
}

export default Hedar
