import { Link } from 'react-router-dom'

const Hedar = () => {
  return (
    <div>
      <Link to="/">Intro</Link>....
      <Link to="/hobbie">Hobbie</Link>....
      <Link to="/contact">Contact</Link>....
      <Link to="/about">About</Link>....
      <Link to="/education">Education</Link>....
      <Link to="/exprince">Exprince</Link>....
      <Link to="/gole">Gole</Link>....
      <Link to="/project">Project</Link>....
      <Link to="/skill">Skill</Link>
    </div>
  )
}

export default Hedar